modLoader="javafml"
loaderVersion="[4,)"  # NeoForge 对应的 FML 加载器版本

# 你的模组许可证（此处填写为 MIT）
license="MIT"

# 你的模组信息
[[mods]]
modId="everlastgear"      # 你的模组ID（必须为小写字母、数字或下划线）
version="1.0.0"               # 你的模组版本号
displayName="Everlast Gear" # 游戏内显示的模组名称

# 你的模组介绍
description='''
'''

logoFile = "everlastgear.png"

# 声明模组作者（可选，建议填写）
# authors="你的名字"
authors="dysakura"
# ---------- 依赖配置 ----------
[[dependencies.everlastgear]]
modId="neoforge"
type="required"
versionRange="[21.1.233,)"
ordering="NONE"
side="BOTH"

[[dependencies.everlastgear]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.2)"
ordering="NONE"
side="BOTH"
